### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > New page

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#1]
Interactive webpage > Linear models with continuous variables > New page

I think we need a page which just introduces what linear models are and sets up the next couple of weeks. At the moment, the student just launches in to the topic. I wrote something last year which we can use/ edit. I was thinking of adding four of figures to help illustrate regression, anova, quadratic and glm.

https://naturalandenvironmentalscience.shinyapps.io/MST2204_regression/#section-what-are-linear-models

**Comment by rasanderson** [comment]
Intro page added based on @willdkreid  version. Accidentally reset wrap to 72 characters but not a problem.
