### ISSUE TITLE
Interactive webpage > Linear models with categorical variables > Introduction

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#10]
Interactive webpage > Linear models with categorical variables > Introduction > Table 1

- edit to give some marine examples e.g. change habitat to marine example for low- , mid- and high-shore

Interactive webpage > Linear models with categorical variables > Introduction > pargraph 1

- edit first sentence - example too vague e.g. "In the previous interactive webpages, we focused on linear models with a continuous exaplanatory variables, that is:"

Interactive webpage > Linear models with categorical variables > Introduction > pargraph 3

-  remove note and astericks

Interactive webpage > Linear models with categorical variables > Introduction > question box

- There are 3 true statements so need to change question e.g. "Which of the following statements are true?"

**Comment by rasanderson** [comment]
Marine example added. Improved formatting of final points - decided to retain as factorial analysis is a commonly used term.
