### ISSUE TITLE
Interactive webpage > Linear models with categorical variables > Example data set

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#11]
Interactive webpage > Linear models with categorical variables > Example data set > new title

- Needs title change e.g. Understanding your data set

Interactive webpage > Linear models with categorical variables > Example data set > paragraph 1

- The data set needs introduced and so do the concepts which we will covered. I woudl also be tempted to start giving them examples of hyptheses and null hypotheses.

  e.g. "We are going to look at a data set that includes a categorical explanatory variable. The data come from an experiment into crop yields on three different soil types, sand, clay and loam. Soil type is the categorical explanatory variable, with three levels (one for each of the three soil types), but in this case we no formal control. The aim is to look at the differences in crop yield among the three levels. We could formulate a hypothesis to test along the lines of:
  There is a significant difference in crop yields among the crop types.
  
  This would mean our null hypothesis would be:
  There is no significant differences in crop yields among the crop types.
  
  First of all lets start by finding out more about our data. We will be using a dataframe called "crop_growth" which includes one explanatory and one response variable. In the R session below, find out the name of the R object `ls()`, look at the first 10 rows `head()`, check how many replicates there are for each of the soil types `nrow()`, and calculate the standard deviations for each soil type.  if you get stuck, look at the hint for more details."

**Comment by rasanderson** [comment]
Changes made as suggested
