### ISSUE TITLE
Interactive webpage > Linear models with categorical variables > Plotting your data

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#12]
Interactive webpage > Linear models with categorical variables > Plotting your data > paragraph 1

- I think we need to hammer home that they need to plot their data first not that it might be useful.

  e.g. "It is always important to visualise your data before undertaking any statistical analyses so that you can see any trends and begin to identify patterns. One of the most useful ways of summarising your data when you have a categorical explanatory variable is via a boxplot. This is because a boxplot provides valuable information about the distribution, spread and central tendency of your data."

Interactive webpage > Linear models with categorical variables > Plotting your data > paragraph 3
- I think adding something about homogeneity of variance along with the boxplots would be good.

- This might be a good place to look at skewed-ness in the data set by compare boxplots and histograms.
  e.g. "The main thing to check is that the spread of the data is roughly the same for each level of your explanatory data, i.e. that the boxes and whiskers are fairly similar and whether the horizontal line is close to the center of the box. Checking the boxplot allows you to assess an important assumption of a linear model which is that the variance is roughly the same at each level. Looking at the spread of data in the boxplots gives us an approximation of whether we have equal variances across the levels. We refer to the equal spread of data across each of the levels as **homogeneity of variance**. If this spread is not equal when comparing among the levels within the categorical variable, we refer to it as **heterogeneity of variance**. There are formal statistical tests which can be used to assess homogeneity of variance but these can be biased by low sample size. In this example, you can see that in your data, they are all approximately the same size, even though the yield overall appears lower for sand. Therefore, we can say that there is homogeneity of variance."

Interactive webpage > Linear models with categorical variables > Plotting your data > paragraph 4 and 5

- remove notch and violin plots

**Comment by rasanderson** [comment]
Changes made as requested. Replaced the 'hint' with a 'solution' for the code box, as essential students see the boxplot.
