### ISSUE TITLE
Interactive webpage > Linear models with categorical variables > What about the individual levels?

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#13]
Interactive webpage > Linear models with categorical variables > What about the individual levels? > paragraph 2

- remove "at"

Interactive webpage > Linear models with categorical variables > What about the individual levels? > paragraph 7

- merge with paragraph 8 and add full stop after 0.020. 

  e.g. "The 95% confidence intervals do not include zero, and so this difference is signficant with p=0.020. This is obvious in the plot where you can see that it is only for the sand vs loam difference that the error bars do not include zero."

Interactive webpage > Linear models with categorical variables > What about the individual levels? > new paragraph

- there needs to be something about writing up the Tukey HSD results

**Comment by rasanderson** [comment]
Issue resolved as requested.
