### ISSUE TITLE
Interactive webpage > Linear models with categorical variables > Check model assumptions

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#14]
Interactive webpage > Linear models with categorical variables > Check model assumptions > new paragraph

- I think we need to add something at the end about testing for heterogeneity of variance in the residuals. What about boxplots of the residuals per soil type? It will reinforce what was mentioned earlier about homogeneity of variance.
- I've also highlighted this for the practical and given a bit of example text & code

**Comment by rasanderson** [comment]
Changes made as suggested, plus new boxplot of residuals (showing code) in the website to confirm issue about homogeneity of variance.
