### ISSUE TITLE
Interactive webpage > Linear models with categorical variables > new page Summary

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#15]
Interactive webpage > Linear models with categorical variables > new page Summary

- I think we need that summary page to round things off so they have clear take home messages i.e. when exactly to use the test, what assumptions need to be met and then a couple of references for them to look up for extra information

Experimental Design and Data Analysis for Biologists Chapter 8 covers one-way ANOVA
Getting started with R for Biologists Chapter 5 covers ANOVA

**Comment by rasanderson** [comment]
Issue resolved as requested
