### ISSUE TITLE
Practical 2 > 3 Regression: Linear models with continuous explanatory variables

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#16]
Practical 2 > 3 Regression: Linear models with continuous explanatory variables > title

- It might be better to put regression at the end because we are thinking of this test within the linear model framework
  e.g. " Linear models with continuous explanatory variables: regression"

**Comment by rasanderson** [comment]
Resolved as requested. Some minor additional changes now that mosaic used directly.
