### ISSUE TITLE
Practical 2 > 3.2 Simple visualisation of caterpillar data

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#17]
Practical 2 > 3.2 Simple visualisation of caterpillar data > paragraph 1

- We need to tell them to plot their data. Otherwise they will just move on.
  e.g. "As you have two fairly simple variables, a scatter plot with our explanatory variable of tannin on the x axis and growth on the y axis will do. Plot your data using the `gf_points()` function, edit the axes labels and make sure there is no grey background. If you can't remember how to do this, refer back to your practical 1 script."

**Comment by rasanderson** [comment]
Issue resolved - gave suggestions as bullet points in the hope students will do this plot.
