### ISSUE TITLE
Practical 2 > 3.4 Plotting the fitted line

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#19]
Practical 2 > 3.4 Plotting the fitted line > new paragraph

- I think we need to get them to plot the 95% confidence intervals around the fitted line so they show can show a measure of uncertainty.
e.g. "We need to illustrate some form of uncertainty around the regression line. The most appropriate method is to add the 95% confidence intervals around the fitted line. We can do this by editing the `gf_lm()` function by adding `interval = "confidence", level = 0.95` to the brackets. When you replot your figure, you will see a grey band appear around the line. This represents the range in which the true regression line can be plotted. In other words, any intercept and slope is potentially possible within this grey area."

Practical 2 > 3.4 Plotting the fitted line > new code box

- Code to include fitting the 95% confidence intervals
e.g. `gf_point(growth~tannin, data = caterpillar_dat) %>% 
  gf_lm(interval = "confidence", level = 0.95) %>%
  gf_labs( y = "Caterpillar growth (mg/day)", x = "Tanin concentration (mg)") %>%
  gf_theme(theme_classic())`

**Comment by rasanderson** [comment]
Issue resolved as suggested.
