### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > Introduction & Plotting the data

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#2]
Interactive webpage > Linear models with continuous variables > Introduction & Plotting the data > whole page

I think this first section needs to cover more on cause and effect, lead them into linear models through correlation and state more clearly when to use regression. This is also partly because you refer to the correlation coefficient a number of times later on but haven't introduced or explained it yet. A structure along the following lines:
1. Introduce continuous variables - keep what is there just now
2. Introduce cause and effect - expand on the issues of cause and effect
3. Introduce correlation - when we don't know which is our explanatory and response variable, do example of correlation using corr.test and lm(), highlight that correlation analyses the simplest form of a strength between variables but does not imply causation - point to other tests section for more details.
4. Introduce linear models with continuous variable - make distinction that linear models are looking more at cause and effect, we clearly know our response and explanatory variables and we are using a statistical model that will explain the relationship between two variables.

Move "The data" section to next page where we start looking properly at linear models

**Comment by rasanderson** [comment]
Issue #2 resolved as recommended
