### ISSUE TITLE
Practical 2 >3.6.2 Residuals from the caterpillar linear model

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#20]
Practical 2 >3.6.2 Residuals from the caterpillar linear model > new paragraph

- We need to add something about checking for homogeneity of variance.
  e.g. "The second assumption that we need to check is that we have equal spread of residuals around the regression line. That is the residuals do not get bigger or smaller as the fitted values change. We can do this by "plotting" the lm object. This is give us a series of plots but we are only interested in in the first two."

Practical 2 >3.6.2 Residuals from the caterpillar linear model > new code box
  `par(mfrow=c(1,2)) # sets two plots side by side in the Plots tab
  plot(growth_lm, which =1:2) # plots the first two diagnostic plots from the lm object
  par(mfrow=c(1,1)) # sets the plotting window back to just one plot`

Practical 2 >3.6.2 Residuals from the caterpillar linear model > new paragraph

- explain ouput
  e.g. "Firstly, we can see the qq-plot again on the right hand side. This follows the same pattern as the one we plotted a minute a go so we can just ignore it. The plot on the left hand side shows our residuals v fitted values and we can see that these are roughly symmetrical around 0. This would indicate that we have no systematic change in the residuals along the fitted values."

**Comment by rasanderson** [comment]
Issue resolved as suggested
