### ISSUE TITLE
Practical 2 > 4 ANOVA: Linear models with categorical explanatory variable

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#21]
Practical 2 > 4 ANOVA: Linear models with categorical explanatory variable > title 

- It might be better to put ANOVA at the end because we are thinking of this test within the linear model framework
e.g. " Linear models with categorcial explanatory variables: ANOVA"

**Comment by rasanderson** [comment]
Issue resolved with revised subheading
