### ISSUE TITLE
Practical 2 > 4.4 Analyse and interpret the linear model

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#23]
Practical 2 > 4.4 Analyse and interpret the linear model > pargarph 5

- Do you want to highlight the Microsoft Teams channel again or just direct them to discuss in person?

**Comment by rasanderson** [comment]
Issue resolved - edits made as suggested, though will probably retain Microsoft Teams for 2023-24 as a more informal way of communication etc.
