### ISSUE TITLE
Practical 2 > 4.5 Multiple comparison tests

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#24]
Practical 2 > 4.5 Multiple comparison tests > paragarph 4

- spelling error - should be "outputs"

Practical 2 > 4.5 Multiple comparison tests > paragarph 4

- I would emphasis that they have to report the Tukey HSD results
e.g. "In both the Tukey table and plot you can see that the only significant pairwise difference is that between sand and loam, where the yield on sand is significantly lower than that on loam. It is important to report the p-value for this comparison as well as the direction and may be the magnitude of this difference."

**Comment by rasanderson** [comment]
Issue resolved as suggested
