### ISSUE TITLE
Practical 2 > 4.6 Check the assumptions of your linear model

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#25]
Practical 2 > 4.6 Check the assumptions of your linear model > new paragraph on looking at homogeneity of variance

- It's worthwhile getting them to look at homogeneity of variance.
  e.g. "We can look to see whether our next important assumption, equal variances for each level, has been met by plotting up the residuals for each level."

Practical 2 > 4.6 Check the assumptions of your linear model > new code box
`gf_point(soil_resids ~ crop_growth$soil)`

Practical 2 > 4.6 Check the assumptions of your linear model > new paragraph

- explain figure adn get them to do a boxplot as another way of looking at it
  e.g. "We can see that the spread of data points is relatively similar across each of the levels in the analysis. This would suggest that we have met our assumption of homogeneity of variance. When we have much larger sample sizes we could look at the residuals using a boxplot. See if you can produce a boxplot of the residuals, overlay the individual residual points and colour those individual points red. You should see that the median value of the boxplots is very close to zero which is good."

`gf_boxplot(soil_resids ~ crop_growth$soil) %>%
  gf_point(soil_resids ~ crop_growth$soil, colour = "red")`

**Comment by rasanderson** [comment]
Issue resolved as suggested. Used gf_jitter instead of gf_point in final boxplot
