### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > Plotting the data

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#4]
Interactive webpage > Linear models with continuous variables > Plotting the data > title

- change to "Data exploration"

remove italicised "interactive R code exercise"

Interactive webpage > Linear models with continuous variables > Plotting the data > paragarph 2

- "In the interactive box below, write Write the R code required calculate the means (averages) of the values in the caterpillers dataframe."

Interactive webpage > Linear models with continuous variables > Plotting the data > code box 1

- add gf_theme(theme_classic()) to get them used to plotting good quality figures

`gf_point(growth ~ tannin, data=caterpillers) %>%
gf_theme(theme_classic())`

**Comment by rasanderson** [comment]
All changes made
