### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > Creating the linear model

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#5]
Interactive webpage > Linear models with continuous variables > Creating the linear model > new paragraph

- I would suggest that we are testing a hypothesis with this statistical test and include a suitable hypothesis and null hypothesis.

Interactive webpage > Linear models with continuous variables > Creating the linear model > paragraph 12

- add new subheading so that it is consistent with above: e.g.

"final three rows

The final three rows give:"

Interactive webpage > Linear models with continuous variables > Creating the linear model > paragraph 12, bullet point 3

- Need to add degrees of freedom e.g. "F-statistic, degrees of freedom and p-value"

Interactive webpage > Linear models with continuous variables > Creating the linear model > paragraph 14

- Need to add something about degrees of freedom here along with the F-statistic

**Comment by rasanderson** [comment]
Some of the info about F, DF and p-values at end of summary output relates to next page of website

**Comment by rasanderson** [comment]
Issue now resolved
