### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > Plotting the fitted line

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#6]
Interactive webpage > Linear models with continuous variables > Plotting the fitted line >  new title

- Model predictions

Interactive webpage > Linear models with continuous variables > Plotting the fitted line > paragarph 1

- Edit first paragarph to say why we want to plot the fitted line - we have found a significant relationship.

Interactive webpage > Linear models with continuous variables > Plotting the fitted line > code box 1

- add gf_theme(theme_classic()) to get them used to plotting good quality figures
`gf_point(growth ~ tannin, data=caterpillers) %>% 
  gf_lm()%>%
gf_theme(theme_classic())`

Interactive webpage > Linear models with continuous variables > Plotting the fitted line > code box 2 & 3

- give solutions to the exercises

Interactive webpage > Linear models with continuous variables > Plotting the fitted line > paragraph 3

- edit sentence for clarity e.g. "The fitted or “predicted” values are those along your straight line, which you have just plotted."

Interactive webpage > Linear models with continuous variables > Plotting the fitted line > new paragarph

- above the code box with "predictor(1:10)" there needs to be a sentence stating what the student is looking at e.g. "We can predict a series of values for growth by giving the predictor function a range of values. In this case, we could ask for predicted value of growth for each whole number between 1 and 10 as follows:"

Interactive webpage > Linear models with continuous variables > Plotting the fitted line > code box 6
- give solutions to the exercises

**Comment by rasanderson** [comment]
Changes made as requested
