### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > Checking model assumptions

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#7]
Interactive webpage > Linear models with continuous variables > Checking model assumptions > paragraph 1

- Need to state what we mean by model assumptions e.g. "All statistical tests have assumptions associated with them and we need to check whether our assumptions have been met so that we know we have undertaken the correct analysis and our subsequent inference from our statistic tests are valid"
- need to state what the assumptions of a linear model are - normaly distributed residuals, homogeneity of variance and independence. We can leave independence to a separate page. I wrote the follwin for independence last year: https://naturalandenvironmentalscience.shinyapps.io/MST2204_regression/#section-a-final-note-independence

Interactive webpage > Linear models with continuous variables > Checking model assumptions > figure 1

- can we include vertical lines between data points and fitted line to highlight what we mean by residuals or keep figure 1 and put new figure in Looking at Residuals section
Interactive webpage > Linear models with continuous variables > Checking model assumptions > paragraph 2

- Need to edit this so it is clear what the residuals are e.g. "Not all your observations fall exactly on the line, as sometimes they are slightly above, and sometimes below. You can see that there is “noise” around the fitted line. The residual for each observation or data point is the difference between the predicted values of y (the line) and the observed value of y. Even if you do an amazingly good experiment, it is very unlikely that they will all fall exactly on the line. You will always have residuals. In some cases, extra explanatory variables can be added to the regression, which will explain more of the variation."

**Comment by rasanderson** [comment]
Use gf_segment to improve graph, and text clarified as suggested
