### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > How to report your results

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#8]
Interactive webpage > Linear models with continuous variables > How to report your results > new title & prargraph

- change the title to "How to write up your analysis" and include something on writing up the data analysis in the methods as well? I'm really tired of having to edit these each year at dissertation time or asking them to put it in.

**Comment by rasanderson** [comment]
Reporting guidelines improved
