### ISSUE TITLE
Interactive webpage > Linear models with continuous variables > new subsection

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical2#9]
Interactive webpage > Linear models with continuous variables > new subsection Summary?

I think it would be good have a summary page with the key points. Direct them to the a couple of resources for additional reading/ self-study. This request comes back each year from our students about where to look for more information to learn about the tests. I think this would help with the students who want to learn more about the statistical tests rather than the coding.

I have a couple of suggestions:
1. Experimental Design adn DAta Analysis for Biologist by Quinn and Keough Chapter 5
2. Getting Started with R Chapter 5
3. Suggest reading Zuur et al A protocol for data exploration to avoid common statistical problems (https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/j.2041-210X.2009.00001.x) - a bit scary and give with a warning but I think gives a really good overview and a workflow.

**Comment by rasanderson** [comment]
Summary and further reading added
